import PushNotification from 'react-native-push-notification';

export default class PushNotificationService {
    lastId: number;

    constructor(onRegister:any, onNotification: any) {
        this.configure(onRegister, onNotification);
        this.lastId = 0;
    }

    configure(onRegister:any, onNotification:any, gcm:string = "") {
        PushNotification.configure(
            {
                onRegister: onRegister,
                onNotification: onNotification,
                senderID: gcm,
                popInitialNotification: true,
                requestPermissions: true
            }
        );
    }

    testNotification():void {
        PushNotification.presentLocalNotification({
            /* Android Only Properties */
            id: '' + this.lastId, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
            ticker: "Wonder-ful Ticker", // (optional)
            autoCancel: true, // (optional) default: true
            largeIcon: "ic_launcher", // (optional) default: "ic_launcher"
            smallIcon: "ic_notification", // (optional) default: "ic_notification" with fallback for "ic_launcher"
            bigText: "Sometimes we need to send a test message to ensure that our systems are working at peak performance levels", // (optional) default: "message" prop
            subText: "This is only a test", // (optional) default: none
            color: "red", // (optional) default: system default
            vibrate: true, // (optional) default: true
            vibration: 300, // vibration length in milliseconds, ignored if vibrate=false, default: 1000
            tag: 'some_tag', // (optional) add tag to message
            group: "group", // (optional) add group to message
            ongoing: false, // (optional) set whether this is an "ongoing" notification

            /* iOS only properties */
            alertAction: 'view', // (optional) default: view
            category: '', // (optional) default: null
            userInfo: {}, // (optional) default: null (object containing additional notification data)
            
            /* iOS and Android properties */
            title: "Wonder Test Message", // (optional)
            message: "You are wonder-ful", // (required)
            playSound: false, // (optional) default: true
            soundName: 'default', // (optional) Sound to play when the notification is shown. Value of 'default' plays the default sound. It can be set to a custom sound such as 'android.resource://com.xyz/raw/my_sound'. It will look for the 'my_sound' audio file in 'res/raw' directory and play it. default: 'default' (default sound is played)
            actions: '["Yes", "No"]',  // (Android only) See the doc for notification actions to know more
        });

        this.lastId++;   
    }
}