# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Hockeyapp Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")

    hockey(
      api_token: "fdd4cf6da60c4122ac8351d834f5ba3c",
      apk: "./app/build/outputs/apk/release/app-release.apk",
      notes: "New Beta Release"
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Upload an APK to HockeyApp"
  lane :upload_to_hockeyapp do
    hockey(
      api_token: "fdd4cf6da60c4122ac8351d834f5ba3c",
      apk: "./app/build/outputs/apk/release/app-release.apk",
      notes: "New Beta Release"
    )
  end
end
